### ISSUE TITLE
Improvement hack idea

### ISSUE THREAD

**Issue by dinkc64** [synamaxmusic/sinistar#2]
Hi SynaMax!
I absolutely love what you're doing!

Would you consider adding your improvement mods to the Cockpit version, to get the super-cool stereoeffects while having a nice balanced game?

Would it be possible to just load the improvement mods w/ the Cockpit sound hw, to avoid having to do any rom mods?

best regards,
- dink

**Comment by dinkc64** [comment]
Hey, I just wanted to say that I pulled this off by taking the synamaxsm (modded romset), creatting a clone called synamaxcsm, adding the 2nd sound cpu & using the cockpit machine.  It was a lot easier than I thought :)

Thanks for your awesome work on Sinistar!

**Comment by synamaxmusic** [comment]
Hi Dink!  Thank you so much for the kind words!  

There are no differences in gameplay between the cockpit and upright versions of Sinistar.  The cockpit version's ROMs are exactly the same as the standard upright version, except for the inclusion of the second sound ROM for the stereo audio.  

You could overwrite the parent Sinistar ROMs inside the MAME /roms folder with the modded ROMs and it would work in the cockpit version, but then you would have to switch out the parent ROMs if you want to preserve the original release (which I think is important), so your solution might be better!

**Comment by dinkc64** [comment]
Thanks buddy, you're the best! :)
